In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [9]:
df=pd.read_csv(r"C:\Users\ASUS\Desktop\csvfiles\mycsv.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
median_number=df.bedrooms.median()

In [11]:
df.bedrooms=df.bedrooms.fillna(median_number)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
reg.intercept_

221323.00186540408

In [17]:
reg.predict([[3000,3,15]])

array([579201.19929613])

In [18]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [44]:
ex_df=pd.read_csv(r"C:\Users\ASUS\Desktop\csvfiles\hiring.csv")
ex_df

experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [45]:
ex_df.experience=ex_df.experience.fillna(0)


In [46]:
ex_median=ex_df.test_score.min()
ex_df.test_score=ex_df.test_score.fillna(ex_median)

In [47]:
ex_df

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         6.0                7   72000
7        11.0         7.0                8   80000

In [48]:
new_reg=linear_model.LinearRegression()
new_reg.fit(ex_df[['experience','test_score','interview_score']],ex_df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
new_reg.predict([[2,5,7]])

array([46790.67749334])